---

- name: Remove the netgroup in /etc/passwd with extra
  lineinfile:
    path: /etc/passwd
    line: "+@{{ item }}:x:::::"
    state: absent
  with_items:
    - "{{net_group_change_netgroups}}"


- name: Remove the netgroup in /etc/passwd
  lineinfile:
    path: /etc/passwd
    regexp: ".@{{ item }}$"
    state: absent
  with_items:
    - "{{net_group_change_netgroups}}"
